/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-27 09:22:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>AeroTrail | Login & Register</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700;800&family=Space+Grotesk:wght@600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Manrope', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #0e4a54 0%, #1a6f7f 50%, #38aa98 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 1fr 1fr;\r\n");
      out.write("            gap: 0;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 30px 80px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .auth-container {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            .auth-visual {\r\n");
      out.write("                display: none !important;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-visual {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(14, 74, 84, 0.95), rgba(56, 170, 152, 0.95));\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 60px 40px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-visual::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            right: -50%;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            animation: float 6s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(-30px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-visual h2 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-family: 'Space Grotesk', sans-serif;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-visual p {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            opacity: 0.95;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-visual-icons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-item svg {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            stroke: white;\r\n");
      out.write("            fill: none;\r\n");
      out.write("            stroke-width: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-item span {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-form-container {\r\n");
      out.write("            padding: 60px 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-header {\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-logo-mark {\r\n");
      out.write("            width: 45px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            background: linear-gradient(135deg, #ff7a18, #ff6b35);\r\n");
      out.write("            display: grid;\r\n");
      out.write("            place-items: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-logo-text {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-logo-name {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #0e4a54;\r\n");
      out.write("            font-family: 'Space Grotesk', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-logo-tag {\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("            color: #8f95a3;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-header h1 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #1a1a1a;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-family: 'Space Grotesk', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-header p {\r\n");
      out.write("            color: #8f95a3;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-tabs {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            border-bottom: 2px solid #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-tab {\r\n");
      out.write("            padding: 12px 0;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: none;\r\n");
      out.write("            color: #8f95a3;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border-bottom: 3px solid transparent;\r\n");
      out.write("            margin-bottom: -2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-tab.active {\r\n");
      out.write("            color: #ff7a18;\r\n");
      out.write("            border-bottom-color: #ff7a18;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-tab:hover:not(.active) {\r\n");
      out.write("            color: #1a1a1a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-panel {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-panel.active {\r\n");
      out.write("            display: block;\r\n");
      out.write("            animation: slideIn 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(10px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            color: #1a1a1a;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 14px 16px;\r\n");
      out.write("            border: 1.5px solid #e0ddd6;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-family: 'Manrope', sans-serif;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            background: #fafaf8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #ff7a18;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            box-shadow: 0 0 0 4px rgba(255, 122, 24, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-input::placeholder {\r\n");
      out.write("            color: #c2b3a3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 24px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-remember {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            color: #8f95a3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-remember input[type=\"checkbox\"] {\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            accent-color: #ff7a18;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-remember label {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-link {\r\n");
      out.write("            color: #ff7a18;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-link:hover {\r\n");
      out.write("            color: #ff6b35;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: linear-gradient(135deg, #ff7a18, #ff6b35);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-family: 'Manrope', sans-serif;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(255, 107, 53, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 15px 35px rgba(255, 107, 53, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn:active {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-footer {\r\n");
      out.write("            margin-top: 24px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #8f95a3;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-footer button {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #ff7a18;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-footer button:hover {\r\n");
      out.write("            color: #ff6b35;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-message {\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-message.success {\r\n");
      out.write("            background: #d4edda;\r\n");
      out.write("            color: #155724;\r\n");
      out.write("            border: 1px solid #c3e6cb;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-message.error {\r\n");
      out.write("            background: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border: 1px solid #f5c6cb;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"auth-container\">\r\n");
      out.write("        <!-- Visual Side -->\r\n");
      out.write("        <div class=\"auth-visual\">\r\n");
      out.write("            <h2>Welcome to AeroTrail</h2>\r\n");
      out.write("            <p>Your gateway to seamless travel planning and unforgettable journeys across the globe.</p>\r\n");
      out.write("            <div class=\"auth-visual-icons\">\r\n");
      out.write("                <div class=\"icon-item\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\">\r\n");
      out.write("                        <path d=\"M12 2L15 10H24L17 15L20 24L12 19L4 24L7 15L0 10H9L12 2Z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <span>Premium Packages</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon-item\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\">\r\n");
      out.write("                        <circle cx=\"12\" cy=\"12\" r=\"10\"/>\r\n");
      out.write("                        <path d=\"M12 6V12L16 14\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <span>24/7 Support</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon-item\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\">\r\n");
      out.write("                        <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <span>Community</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Form Side -->\r\n");
      out.write("        <div class=\"auth-form-container\">\r\n");
      out.write("            <c:set var=\"isLogin\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mode ne 'register'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("            <div class=\"auth-logo\">\r\n");
      out.write("                <div class=\"auth-logo-mark\">A</div>\r\n");
      out.write("                <div class=\"auth-logo-text\">\r\n");
      out.write("                    <div class=\"auth-logo-name\">AeroTrail</div>\r\n");
      out.write("                    <div class=\"auth-logo-tag\">Travel Management</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"auth-header\">\r\n");
      out.write("                <h1 id=\"authTitle\">Welcome back</h1>\r\n");
      out.write("                <p id=\"authSubtitle\">Sign in to continue your journey</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"auth-tabs\">\r\n");
      out.write("                <button class=\"auth-tab ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogin ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"switchTab(event, 'login')\">Login</button>\r\n");
      out.write("                <button class=\"auth-tab ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!isLogin ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"switchTab(event, 'register')\">Register</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <div class=\"auth-message ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.contains('success') ? 'success' : 'error'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </c:if>\r\n");
      out.write("\r\n");
      out.write("            <!-- Login Panel -->\r\n");
      out.write("            <form id=\"loginPanel\" class=\"auth-panel ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogin ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"login-email\">Email Address</label>\r\n");
      out.write("                    <input type=\"email\" id=\"login-email\" name=\"email\" class=\"form-input\" placeholder=\"your@email.com\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"login-password\">Password</label>\r\n");
      out.write("                    <input type=\"password\" id=\"login-password\" name=\"password\" class=\"form-input\" placeholder=\"••••••••\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <label class=\"form-remember\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"remember\">\r\n");
      out.write("                        <span>Remember me</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <a href=\"#\" class=\"form-link\" data-toast=\"Please contact support to reset your password.\">Forgot password?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\">Sign In</button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"auth-footer\">\r\n");
      out.write("                    Don't have an account? <button type=\"button\" onclick=\"switchTab(event, 'register')\">Create one</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Register Panel -->\r\n");
      out.write("            <form id=\"registerPanel\" class=\"auth-panel ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!isLogin ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/users/add\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"register-name\">Full Name</label>\r\n");
      out.write("                    <input type=\"text\" id=\"register-name\" name=\"name\" class=\"form-input\" placeholder=\"John Doe\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"register-email\">Email Address</label>\r\n");
      out.write("                    <input type=\"email\" id=\"register-email\" name=\"email\" class=\"form-input\" placeholder=\"your@email.com\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"register-phone\">Phone Number</label>\r\n");
      out.write("                    <input type=\"tel\" id=\"register-phone\" name=\"phone\" class=\"form-input\" placeholder=\"+1 (555) 000-0000\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"register-password\">Password</label>\r\n");
      out.write("                    <input type=\"password\" id=\"register-password\" name=\"password\" class=\"form-input\" placeholder=\"••••••••\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-remember\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"terms\" required>\r\n");
      out.write("                        <span>I agree to the Terms & Conditions</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\">Create Account</button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"auth-footer\">\r\n");
      out.write("                    Already a member? <button type=\"button\" onclick=\"switchTab(event, 'login')\">Sign in</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function switchTab(e, tab) {\r\n");
      out.write("            if (e) e.preventDefault();\r\n");
      out.write("            \r\n");
      out.write("            const loginPanel = document.getElementById('loginPanel');\r\n");
      out.write("            const registerPanel = document.getElementById('registerPanel');\r\n");
      out.write("            const tabs = document.querySelectorAll('.auth-tab');\r\n");
      out.write("            const title = document.getElementById('authTitle');\r\n");
      out.write("            const subtitle = document.getElementById('authSubtitle');\r\n");
      out.write("\r\n");
      out.write("            tabs.forEach(t => t.classList.remove('active'));\r\n");
      out.write("            \r\n");
      out.write("            if (tab === 'login') {\r\n");
      out.write("                loginPanel.classList.add('active');\r\n");
      out.write("                registerPanel.classList.remove('active');\r\n");
      out.write("                tabs[0].classList.add('active');\r\n");
      out.write("                title.textContent = 'Welcome back';\r\n");
      out.write("                subtitle.textContent = 'Sign in to continue your journey';\r\n");
      out.write("            } else {\r\n");
      out.write("                registerPanel.classList.add('active');\r\n");
      out.write("                loginPanel.classList.remove('active');\r\n");
      out.write("                tabs[1].classList.add('active');\r\n");
      out.write("                title.textContent = 'Create your account';\r\n");
      out.write("                subtitle.textContent = 'Join our travel community today';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
